package:
  name: automech-toolbox
  version: "2024.5.24"

source:
  path: .

build:
  noarch: generic
  script:
    - mkdir -p ${PREFIX}/bin
    - mkdir -p ${PREFIX}/share
    - cp ${RECIPE_DIR}/../static/bin/* ${PREFIX}/bin/.
    - cp ${RECIPE_DIR}/../static/share/* ${PREFIX}/bin/.
